FROM localhost:5000/zephyr-mica-scratch
# FROM zephyr-mica-scratch

# default FIRMWARE_BUNDLE_PATH is <container_root>/zephyr.elf
ARG FIRMWARE_BUNDLE_PATH="/zephyr.elf"
# firmware source path
ARG FIRMWARE="zephyr.elf"

COPY ${FIRMWARE} ${FIRMWARE_BUNDLE_PATH}
LABEL org.opencontainer.image.mica.firmware="${FIRMWARE_BUNDLE_PATH}"
LABEL org.opencontainer.image.mica.pedestal_conf=""

# Necessary for mica runtime to check the pedestal
LABEL org.opencontainer.image.mica.pedestal="baremetal"
LABEL org.opencontainer.image.mica.platform_config=""
LABEL org.opencontainer.image.mica.compatibility.openamp="2023.04+"
LABEL org.opencontainer.image.mica.compatibility.zephyr="3.7.1"

ADD qemu-zephyr-rproc.conf ${defs.DefaultClientConf}
# Inherit from zephyr-mica-scratch
CMD ["/hello"]