FROM localhost:5000/zephyr-mica-scratch

# default FIRMWARE_BUNDLE_PATH is <container_root>/zephyr.elf
ARG FIRMWARE_BUNDLE_PATH="/firmware.elf"
ARG XEN_BIN_IMG="/image.bin"

LABEL org.opencontainer.image.description="Mica Zephyr Hello World Sample(based on xen)"

# Necessary for mica runtime to check the pedestal
LABEL org.openeuler.mica.pedestal_conf="${XEN_BIN_IMG}"
LABEL org.opencontainer.image.mica.compatibility.zephyr="3.7.1"

ADD bundle.sample/zephyr.xen.elf ${FIRMWARE_BUNDLE_PATH}
ADD bundle.sample/zephyr.xen.bin ${XEN_BIN_IMG}