# this image is built as zephyr-mica-scratch:latest
#FROM mica-scratch
FROM scratch

# For image builder based on scratch image, these labels can be overridden 
# but some of which are not recommended to be overridden

# Ok to be customized:
LABEL org.opencontainer.image.description="Zephyr scratch image"
LABEL org.openeuler.mica.pedestal="baremetal"
LABEL org.openeuler.mica.pedestal_conf=""
LABEL org.openeuler.mica.compatibility.openamp="2023.04+"
LABEL org.openeuler.mica.compatibility.zephyr="3.7.1+"

# Not recommended to be overridden:
# OS name
LABEL org.openeuler.mica.os="zephyr"

# add a sample config file
ADD linux-tiny-hello/hello_gcc /hello

CMD ["/hello"]